[book]
title = "El Lenguaje de Programación Rust"
author = "Steve Klabnik y Carol Nichols, con la Contribución de la Comunidad Rust"


[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css"]
additional-js = ["ferris.js"]
git-repository-url = "https://github.com/rust-lang/book"
